<a href="https://colab.research.google.com/github/tabssum/Python_Assignments_yaminsir-s_class/blob/main/data_science_assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# row wise sum of element
np.sum(a, axis=1)

array([ 6, 15, 24])

In [6]:
# Colume wise sum of number
np.sum(a, axis=0)

array([12, 15, 18])

In [7]:
# A row wise min
np.min(a, axis=1)

array([1, 4, 7])

In [8]:
# A column wise min
np.min(a, axis=0)

array([1, 2, 3])

In [9]:
# A row wise max
np.max(a, axis=1)

array([3, 6, 9])

In [11]:
#A colum wise max
np.max(a, axis=0)

array([7, 8, 9])

In [12]:
# row wise mean
np.mean(a,axis=1)

array([2., 5., 8.])

In [13]:
# Colum wise mean
np.mean(a,axis=0)

array([4., 5., 6.])

In [14]:
#row wise standard deviation
np.std(a,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [16]:
#A columnn wise standard deviation
np.std(a,axis=0)

array([2.44948974, 2.44948974, 2.44948974])