<a href="https://colab.research.google.com/github/tabssum/Python_Assignments_yaminsir-s_class/blob/main/data_science_assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# row wise sum of element
np.sum(a, axis=1)

array([ 6, 15, 24])

In [6]:
# Colume wise sum of number
np.sum(a, axis=0)

array([12, 15, 18])

In [7]:
# A row wise min
np.min(a, axis=1)

array([1, 4, 7])

In [8]:
# A column wise min
np.min(a, axis=0)

array([1, 2, 3])

In [9]:
# A row wise max
np.max(a, axis=1)

array([3, 6, 9])

In [11]:
#A colum wise max
np.max(a, axis=0)

array([7, 8, 9])

In [12]:
# row wise mean
np.mean(a,axis=1)

array([2., 5., 8.])

In [13]:
# Colum wise mean
np.mean(a,axis=0)

array([4., 5., 6.])

In [14]:
#row wise standard deviation
np.std(a,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [16]:
#A columnn wise standard deviation
np.std(a,axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [35]:
#create a 3*3 array
nd_array_random=np.random.random((3,3))
print(f" Array with random numbers \n {nd_array_random} \n")

nd_array=np.arange(8)
nd_array.resize((1,8))
print(f" Array with range numbers \n {nd_array} \n")
#Find its shape
print(f"Shape of array : {nd_array.shape} \n")
#Reshape 1D array into 2*4 array
nd_array.reshape((2,4))
# Find the sum,mean,min,max values
print(f"Sum of elements : {nd_array.sum()}")
print(f"Min of elements : {nd_array.min()}")
print(f"Max of elements : {nd_array.max()}")
print(f"Mean of elements : {nd_array.mean()}")
# Calculate the median and Standard deviation
print(f"Sum of elements : {np.median(nd_array)}")
print(f"Sum of elements : {nd_array.std()}")



 Array with random numbers 
 [[0.61806934 0.73812748 0.12810545]
 [0.51782604 0.47769488 0.48748244]
 [0.83607638 0.77637805 0.04977342]] 

 Array with range numbers 
 [[0 1 2 3 4 5 6 7]] 

Shape of array : (1, 8) 

Sum of elements : 28
Min of elements : 0
Max of elements : 7
Mean of elements : 3.5
Sum of elements : 3.5
Sum of elements : 2.29128784747792
